// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRaXHG_SVxdN-G0E4YiW-dNxiJkNEyaU',
    appId: '1:942151390727:web:a724bca5f23a0c78f1fca2',
    messagingSenderId: '942151390727',
    projectId: 'nitantlms',
    authDomain: 'nitantlms.firebaseapp.com',
    databaseURL: 'https://nitantlms-default-rtdb.firebaseio.com',
    storageBucket: 'nitantlms.appspot.com',
    measurementId: 'G-J88BCXHFYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLgJeyNETZT_Op5FGCbtMZJmCA2avcww',
    appId: '1:942151390727:android:fa9a38eb583b03fff1fca2',
    messagingSenderId: '942151390727',
    projectId: 'nitantlms',
    databaseURL: 'https://nitantlms-default-rtdb.firebaseio.com',
    storageBucket: 'nitantlms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9D3jKNuW29KF9tqb762z8EF3kQyfnWY',
    appId: '1:942151390727:ios:b82f2c3916b83c4cf1fca2',
    messagingSenderId: '942151390727',
    projectId: 'nitantlms',
    databaseURL: 'https://nitantlms-default-rtdb.firebaseio.com',
    storageBucket: 'nitantlms.appspot.com',
    iosClientId: '942151390727-uuc26dq25utq7fgmko8k6jor898u7u29.apps.googleusercontent.com',
    iosBundleId: 'com.guider.guider2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9D3jKNuW29KF9tqb762z8EF3kQyfnWY',
    appId: '1:942151390727:ios:3a9b9462acf0862bf1fca2',
    messagingSenderId: '942151390727',
    projectId: 'nitantlms',
    databaseURL: 'https://nitantlms-default-rtdb.firebaseio.com',
    storageBucket: 'nitantlms.appspot.com',
    iosClientId: '942151390727-80cbft8c79pdbg60d1d3ark394jjdodv.apps.googleusercontent.com',
    iosBundleId: 'com.guider.guider2.RunnerTests',
  );
}
